### ISSUE TITLE
working with safari (mac/ios)?

### ISSUE THREAD

**Issue by triple7** [ai/offscreen-canvas#31]
Been looking for a way to off load canvas manipulation and this seems to be the solution, as webkit nightly don't have any offscreenCanvas functionality. Is this working with safari?

**Comment by ai** [comment]
It will work, but use normal canvas without offscreen and web worker

**Comment by triple7** [comment]
Thanks for the clarification. So it works with canvas, and have you tried 2D canvas and drawing images, graphicsContext('2d'), path, clip and matrix transform? Sorry for asking all of these, but these functions are required for my simulation.

Thanks for any pointer

**Comment by ai** [comment]
> So it works with canvas, and have you tried 2D canvas and drawing images, graphicsContext('2d'), path, clip and matrix transform?

Nope. I used only three.js
