### ISSUE TITLE
Pass extra data to worker

### ISSUE THREAD

**Issue by unlocomqx** [ai/offscreen-canvas#4]
In my use case, I'm converting a SVG to JPG so I need to pass the svg code to the worker.
It would be better if the `createWorker` function would accept a `data` argument to pass arbitrary data

PS: I can assign the svg code to the `canvas` dataset for now

**Comment by ai** [comment]
You can send additional message with converted data:

```js
worker.post({ message: 'image', image: jpg })
```

It is better because SVG→JPG conversion can take a while and you can load OffscreenCanvas while an image is loading.

Will it help you?

**Comment by unlocomqx** [comment]
Yes, I will try it 

Thank you
